name: PR Gate

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install flake8
        run: pip install -r requirements-flake8.txt

      - name: Run flake8
        run: flake8 src/pyrona tests

  linux:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python ${{matrix.python_version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}
          architecture: x64

      - name: Install the package
        run: pip install -e .[test]

      - name: Run tests
        uses: pavelzw/pytest-action@v1
        with:
          verbose: true
          job_summary: true
          emoji: true
