name: PR Gate

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install the package
        run: pip install -e .[linting]

      - name: Run flake8
        run: flake8 src/pyrona tests

  linux:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
          architecture: x64

      - name: Install the package
        run: pip install -e .[test]

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          job_summary: true
          emoji: true

  windows:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
          architecture: x64

      - name: Install the package
        run: pip install -e .[test]

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          job_summary: true
          emoji: true

  macos:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
          architecture: x64

      - name: Install the package
        run: pip install -e .[test]

      - name: Python test
        run: pytest -vv --emoji